plugins {
    id "com.android.application" version "8.6.0" apply false
    // ENSURE THIS LINE IS 1.9.24
    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
